### ISSUE TITLE
Ad Quality SDK

### ISSUE THREAD

**Issue by dri-richard** [defold/extension-ironsource#20]
- [ ] Android https://developers.is.com/ironsource-mobile/android/sdk-integration-guides/
- [ ] iOS https://developers.is.com/ironsource-mobile/ios/sdk-integration-guides/

**Comment by britzl** [comment]
Adding Ad Quality SDK later than 7.15.0 will result in a runtime crash when calling `IronSourceAdQuality.getInstance()`:

```
W  java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
W  	at com.ironsource.adqualitysdk.sdk.i.e.<clinit>(Unknown Source:3000)
W  	at com.ironsource.adqualitysdk.sdk.i.aw.a(:195)
W  	at com.ironsource.adqualitysdk.sdk.i.aw.<init>(:13)
W  	at com.ironsource.adqualitysdk.sdk.i.z.<init>(:73)
W  	at com.ironsource.adqualitysdk.sdk.i.z.ﻛ(:67)
W  	at com.ironsource.adqualitysdk.sdk.IronSourceAdQuality.getInstance(:23)
```

One change between 7.15.0 and 7.16.0+ is that the sdk contains shared objects:

![image](https://github.com/defold/extension-ironsource/assets/1300688/2c4f3169-d1fc-45e4-a79a-be7fbb26bd56)

The extender server is sending these back to the client:

https://github.com/defold/extender/blob/dev/server/src/main/java/com/defold/extender/Extender.java#L2346

And bob will include them in the .aab:

<img width="397" alt="Screenshot 2024-05-19 at 10 49 47" src="https://github.com/defold/extension-ironsource/assets/1300688/f2bea4d2-df7d-4a77-851f-ebd6070f3889">

My assumption now is that the .so files are compressed and the manifest doesn't specify to unpack them using `android:extractNativeLibs`:

https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs

The bundletool accepts a config json file which can specify a glob pattern for files that should not be compressed:

https://github.com/google/bundletool/blob/master/src/test/java/com/android/tools/build/bundletool/commands/BuildBundleCommandTest.java#L130-L133

**Comment by AGulev** [comment]
@britzl for now we create it in code, but we can move it into a file similar to what we have for AndroidManifes: https://github.com/defold/defold/blob/582fd1c9c139ccd0a324842b6247dfdc9131c152/com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/AndroidBundler.java#L690-L692

**Comment by britzl** [comment]
Ah, we already do this. Hmm, yeah, we need to think about if we want to have `extractNativeLibs` as a game.project option and inject it into the AndroidManifest.xml, and if set to false, we add a glob pattern for .so files in AndroidBundler.java

**Comment by AGulev** [comment]
> Adding Ad Quality SDK later than 7.15.0 will result in a runtime crash when calling `IronSourceAdQuality.getInstance()`:
> 
> ```
> W  java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[], int, int)' on a null object reference
> W  	at com.ironsource.adqualitysdk.sdk.i.e.<clinit>(Unknown Source:3000)
> W  	at com.ironsource.adqualitysdk.sdk.i.aw.a(:195)
> W  	at com.ironsource.adqualitysdk.sdk.i.aw.<init>(:13)
> W  	at com.ironsource.adqualitysdk.sdk.i.z.<init>(:73)
> W  	at com.ironsource.adqualitysdk.sdk.i.z.ﻛ(:67)
> W  	at com.ironsource.adqualitysdk.sdk.IronSourceAdQuality.getInstance(:23)
> ```
> 
> One change between 7.15.0 and 7.16.0+ is that the sdk contains shared objects:
> 
> ![image](https://private-user-images.githubusercontent.com/1300688/331858843-2c4f3169-d1fc-45e4-a79a-be7fbb26bd56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTI1MzYsIm5iZiI6MTcxNjExMjIzNiwicGF0aCI6Ii8xMzAwNjg4LzMzMTg1ODg0My0yYzRmMzE2OS1kMWZjLTQ1ZTQtYTc5YS1iZTdmYmIyNmJkNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMDk1MDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Q2YWFjMzU3ZWIwYTQ2YzU0NGQxMWE2NTE0NzZkMWEzNzVjYzZiNjAzYTY5Njg0NzFlNTZmMzExOTgzYmNmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0YK6AyxU8RHUoEogbkAhZg9ieFRRsVHqwUd0qWbR0Is)
> 
> The extender server is sending these back to the client:
> 
> https://github.com/defold/extender/blob/dev/server/src/main/java/com/defold/extender/Extender.java#L2346
> 
> And bob will include them in the .aab:
> 
> <img alt="Screenshot 2024-05-19 at 10 49 47" width="397" src="https://private-user-images.githubusercontent.com/1300688/331858949-f2bea4d2-df7d-4a77-851f-ebd6070f3889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTI1MzYsIm5iZiI6MTcxNjExMjIzNiwicGF0aCI6Ii8xMzAwNjg4LzMzMTg1ODk0OS1mMmJlYTRkMi1kZjdkLTRhNzctODUxZi1lYmQ2MDcwZjM4ODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMDk1MDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM3OTZiODQ0MWRiZjUyNTYxZDE3YzlmNTUxNzIzOTJjNmFlMjIwZTlkYjM4YWE5OTFiNWNkOGU2NzRhOGY1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fHTXiVot-9NcPpiUtKVx0Rbw4DH1aQ9big5xehQqEXo">
> My assumption now is that the .so files are compressed and the manifest doesn't specify to unpack them using `android:extractNativeLibs`. It is however recommended to not compress the shared objects and not extract them.
> 
> https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs
> 
> The bundletool accepts a config json file which can specify a glob pattern for files that should not be compressed:
> 
> https://github.com/google/bundletool/blob/master/src/test/java/com/android/tools/build/bundletool/commands/BuildBundleCommandTest.java#L130-L133

It should be easy to test, I think, by manual apk repacking. Just to make sure it helps
