### ISSUE TITLE
bidmachine_android and mytarget_android not builded for android

### ISSUE THREAD

**Issue by d954mas** [defold/extension-ironsource#23]
* What went wrong:
Execution failed for task ':downloadDependencies'.
> Could not resolve all dependencies for configuration ':releaseRuntimeClasspath'.
   > Could not resolve io.bidmachine:ads.networks.gam:2.4.0.+.
     Required by:
         project : > io.bidmachine:ads:2.4.0
      > Failed to list versions for io.bidmachine:ads.networks.gam.
         > Unable to load Maven meta-data from https://artifactory.bidmachine.io/bidmachine/io/bidmachine/ads.networks.gam/maven-metadata.xml.
            > org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
   > Could not resolve io.bidmachine:ads.networks.notsy:2.4.0.+.
     Required by:
         project : > io.bidmachine:ads:2.4.0
      > Failed to list versions for io.bidmachine:ads.networks.notsy.
         > Unable to load Maven meta-data from https://artifactory.bidmachine.io/bidmachine/io/bidmachine/ads.networks.notsy/maven-metadata.xml.
            > org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
   > Could not resolve io.bidmachine:ads.networks.appodeal_gam:2.4.0.+.
     Required by:
         project : > io.bidmachine:ads:2.4.0
      > Failed to list versions for io.bidmachine:ads.networks.appodeal_gam.
         > Unable to load Maven meta-data from https://artifactory.bidmachine.io/bidmachine/io/bidmachine/ads.networks.appodeal_gam/maven-metadata.xml.
            > org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
   > Could not resolve io.bidmachine:ads.networks.a4g:2.4.0.+.
     Required by:
         project : > io.bidmachine:ads:2.4.0
      > Failed to list versions for io.bidmachine:ads.networks.a4g.
         > Unable to load Maven meta-data from https://artifactory.bidmachine.io/bidmachine/io/bidmachine/ads.networks.a4g/maven-metadata.xml.
            > org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
   > Could not resolve com.my.tracker:mytracker-sdk:[3.0.0,3.1.0).
     Required by:
         project : > com.my.target:mytarget-sdk:5.19.0
      > Failed to list versions for com.my.tracker:mytracker-sdk.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/com/my/tracker/mytracker-sdk/maven-metadata.xml.
            > org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
            
            
[log.txt](https://github.com/defold/extension-ironsource/files/15307845/log.txt)

Defold 1.8.0

set them to 0 project builded

bidmachine_android = 0
mytarget_android = 0

**Comment by AGulev** [comment]
will be fixed with the next update (will work only with new Defold 1.8.2)
