### ISSUE TITLE
adcolony_android Adapter - MISSING

### ISSUE THREAD

**Issue by d954mas** [defold/extension-ironsource#24]
[iron_source]
adcolony_android = 1

ironsource.validate_integration()

 I  --------------- AdColony --------------
 E  Adapter - MISSING
 E  >>>> AdColony - NOT VERIFIED

**Comment by AGulev** [comment]
there is no such adapter for Android: https://developers.is.com/ironsource-mobile/android/superawesome-integration-guide/#step-3

![CleanShot 2024-06-01 at 22 23 43@2x](https://github.com/defold/extension-ironsource/assets/2209596/1aefe425-3672-4ee8-a4e5-0a5a8f895992)

**Comment by d954mas** [comment]
If not mb you should remove this from game.project?

https://github.com/defold/extension-ironsource/blob/bf8c39f1cf80b242f2871ce0c7ebe48ab3f22e49/game.project#L25

**Comment by d954mas** [comment]
https://stackoverflow.com/questions/77792203/ironsource-mediation-adcolony-adapter-called-fyber-now-and-is-not-found

Looks like adcolony is not used now

**Comment by AGulev** [comment]
It will be removed in the nextnupdate
